### ISSUE TITLE
[HomeScreen] Populate each item in FlatLists with the returned data

### ISSUE THREAD

**Issue by sunwukonga** [sunwukonga/BBB#56]

**Comment by evgeetha** [comment]
Already we have used Flat lists with the returned data.  
Can you provide more detail what we have to accomplish?

**Comment by sunwukonga** [comment]
Just linking all of the data up and hardening it in the case of missing data.

I'm doing this right now actually.

* primaryImage (currently replacing former default with Baby icon)
* user
  * Id
  * username
  * profileImage
* title // description
* currency + price
* liked + chatId
* verification
* sellerRating + count
